Import Necessary Packages

In [ ]:
import pandas as pd
import numpy as np
import os

Import Excel File \
**ACTION REQUIRED**

In [ ]:
file_path = 'FILE PATH'\FY2425 A and M Inv Sales December YTD_v2.xlsx'
sheet_name = 'Invoice Details FY2324 - FY2425'
df = pd.read_excel(file_path, sheet_name=sheet_name)

df.head()

,Aviation/ LY/CM,Effective Period,Effective FY,ID,Fin Year,Finance Period,Region,Market,LOB,Territory,...,Batch Number,Legal Entity,Mgt Company,Measurement QTY,OEMEnd User,Warehouse,Type,contractual/ Trans,Transactional,Russian?
0,LY,1,2023-2024,GP14-1328615,2023-2024,1,ROW,LY-MED,LY,US YACHT,...,0731 LYE CS,MED,NaN,0.0,,MEDSPACE,Actual,Transactional,NaN,NaN
1,LY,1,2023-2024,GP14-1328665,2023-2024,1,ROW,LY-MED,LY,US YACHT,...,0731 LYE CS,MED,NaN,0.0,,MEDSPACE,Actual,Transactional,NaN,NaN
2,LY,1,2023-2024,GP14-1328666,2023-2024,1,ROW,LY-MED,LY,US YACHT,...,0731 LYE CS,MED,NaN,0.0,,MEDSPACE,Actual,Transactional,NaN,NaN
3,LY,1,2023-2024,GP14-1328667,2023-2024,1,ROW,LY-MED,LY,US YACHT,...,0731 LYE CS,MED,NaN,0.0,,MEDSPACE,Actual,Transactional,NaN,NaN
4,LY,1,2023-2024,GP14-1328668,2023-2024,1,ROW,LY-MED,LY,US YACHT,...,0731 LYE CS,MED,NaN,0.0,,MEDSPACE,Actual,Transactional,NaN,NaN

Retrieve All Columns

In [ ]:
for col in df.columns:
    print(col)

Aviation/ LY/CM
Effective Period
Effective FY
ID
Fin Year
Finance Period
Region
Market
LOB
Territory
Sales Person ID
Sales Person
Selling Office
Category
Product
Customer
Customer Name
Invoice Number
Invoice Date
Price
GP Sold Percent
GP Sold Amount (USD)
Orig Order Number
Item Number
Item Class
Item Description
Catalog Unit Measure
Catalog Price
Item Qty
Unit Measure Sold
Price per Unit Sold
Currency
Amount Source Currency
Functional Currency
Exchange Rate To USD
Exchange Rate To Functional Currency
Tail Number
Effective Date
Expiration Date
Cash/Vouch
Payment Terms
Invoice Source
Batch Number
Legal Entity
Mgt Company
Measurement QTY
OEMEnd User
Warehouse
Type
contractual/ Trans
Transactional
Russian?

Drop Unneccessary Columns

In [ ]:
columns_to_drop = ['Effective FY',
                   'ID',
                   'Territory',
                   'Sales Person ID',
                   'Sales Person',
                   'Customer',
                   'Customer Name',
                   'GP Sold Percent',
                   'GP Sold Amount (USD)',
                   'Item Class',
                   'Catalog Unit Measure',
                   'Catalog Price',
                   'Unit Measure Sold',
                   'Price per Unit Sold',
                   'Currency',
                   'Amount Source Currency',
                   'Functional Currency',
                   'Exchange Rate To USD',
                   'Exchange Rate To Functional Currency',
                   'Tail Number',
                   'Cash/Vouch',
                   'Payment Terms',
                   'Invoice Source',
                   'Batch Number',
                   'Legal Entity',
                   'Mgt Company',
                   'Measurement QTY',
                   'OEMEnd User',
                   'Warehouse',
                   'Transactional',
                   'Russian?',
                   'Orig Order Number',
                   'Item Number',
                   'Selling Office',
                   'Invoice Number',
                   'Item Description',
                   'Item Qty'
                   ]
df = df.drop(columns=columns_to_drop)

Columns Used

In [ ]:
for col in df.columns:
    print(col)

Aviation/ LY/CM
Effective Period
Fin Year
Finance Period
Region
Market
LOB
Category
Product
Invoice Date
Price
Effective Date
Expiration Date
Type
contractual/ Trans

Filtering Data | 'Type' = Actual | 'contractual/ Trans' = Contractual | 'Fin Year' = '2024-2025', '2023-2024'

In [ ]:
filtered_df = df[(df['Type'] != 'Budget') & (df['contractual/ Trans'] == 'Contractual') & (df['Fin Year'].isin(['2024-2025', '2023-2024']))]

Correct Filtering

In [ ]:
filtered_df.tail()

,Aviation/ LY/CM,Effective Period,Fin Year,Finance Period,Region,Market,LOB,Category,Product,Invoice Date,Price,Effective Date,Expiration Date,Type,contractual/ Trans
119669,LY,7,2024-2025,6,EUROPE,LY-MDK,LY,RNW,Membership & Security,2024-12-31,1267.427100,2025-01-28,2026-01-27,Actual,Contractual
119670,LY,3,2024-2025,6,EUROPE,LY-MDK,LY,RNW,Membership & Security,2024-12-31,-798.479073,2021-09-17,2022-12-16,Actual,Contractual
119671,LY,3,2024-2025,6,EUROPE,LY-MDK,LY,RNW,Expertise,2024-12-31,-2544.359903,2021-09-17,2022-12-16,Actual,Contractual
119672,CM,5,2024-2025,6,APAC,CM,CM,RNW,Expertise,2024-12-31,43056.720000,2024-11-17,2025-11-16,Actual,Contractual
129739,CM,5,2023-2024,7,APAC,CM,CM,RNW,Expertise,NaT,35149.320000,2023-11-17,2024-11-16,Actual,Contractual

NA Values

In [ ]:
filtered_df.isnull().sum()

Aviation/ LY/CM       0
Effective Period      0
Fin Year              0
Finance Period        0
Region                0
Market                0
LOB                   0
Category              0
Product               0
Invoice Date          1
Price                 0
Effective Date        0
Expiration Date       0
Type                  0
contractual/ Trans    0
dtype: int64

Ensure Correct Data Types

In [ ]:
# Get data types of all columns
column_data_types = filtered_df.dtypes

# Print the data types
print(column_data_types)

Aviation/ LY/CM               object
Effective Period               int64
Fin Year                      object
Finance Period                 int64
Region                        object
Market                        object
LOB                           object
Category                      object
Product                       object
Invoice Date          datetime64[ns]
Price                        float64
Effective Date        datetime64[ns]
Expiration Date       datetime64[ns]
Type                          object
contractual/ Trans            object
dtype: object

New CSV Data Frame Information

In [ ]:
filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11500 entries, 1548 to 129739
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Aviation/ LY/CM     11500 non-null  object
 1   Effective Period    11500 non-null  int64
 2   Fin Year            11500 non-null  object
 3   Finance Period      11500 non-null  int64
 4   Region              11500 non-null  object
 5   Market              11500 non-null  object
 6   LOB                 11500 non-null  object
 7   Category            11500 non-null  object
 8   Product             11500 non-null  object
 9   Invoice Date        11499 non-null  datetime64[ns]
 10  Price               11500 non-null  float64
 11  Effective Date      11500 non-null  datetime64[ns]
 12  Expiration Date     11500 non-null  datetime64[ns]
 13  Type                11500 non-null  object
 14  contractual/ Trans  11500 non-null  object
dtypes: datetime64[ns](3), float64(1), int64(2), object(9)
memory usage: 1.4+ MB

Export New CSV File for PowerBI \
**ACTION REQUIRED**

In [ ]:
# Get the directory of the original file
file_path = 'FILE PATH'/FY2425 A and M Inv Sales December YTD_v2.xlsx'
file_directory = os.path.dirname(file_path)

# Construct the output file path
output_file_path = os.path.join(file_directory, 'FY2425 A and M Inv Sales December YTD PowerBI.csv')

# Write the DataFrame to a CSV file
filtered_df.to_csv(output_file_path, index=False)

print(f"DataFrame saved to: {output_file_path}")